runtime: python
env: flex
entrypoint: gunicorn -b :8080 main:app
runtime_config:
  python_version: 3

# App Engine has 1 CPU, 4 GB RAM, 32 GB disk space.
# TODO: Can probably decrease the disk space?
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 32
